name: DarkOakBan
main: sh.kaden.darkoakban.DarkOakBanPlugin
version: 2.0.0
description: Bans players daring enough to use dark oak signs.
author: webcrawls <kadenscott>
website: https://github.com/webcrawls/DarkOakBan
api-version: '1.21.1'